id: P005483
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ674
  title: མི་ཕམ་བློ་གྲོས་རྒྱ་མཚོའི་དྲང་གཏམ
  author: ''
  volumes:
    3ed9bd31e8544f71a822fb893cbd952d:
      image_group_id: I1CZ685
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
