id: P005483
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 11:52:57.230503
source_metadata:
  id: bdr:W1CZ674
  title: མི་ཕམ་བློ་གྲོས་རྒྱ་མཚོའི་དྲང་གཏམ
  author: ''
  volumes:
    3ed9bd31e8544f71a822fb893cbd952d:
      image_group_id: I1CZ685
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
