id: I3704763D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:38:16+00:00'
last_modified: '2022-06-08T03:24:33.508229+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ674
  title: མི་ཕམ་བློ་གྲོས་རྒྱ་མཚོའི་དྲང་གཏམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    24AF:
      image_group_id: I1CZ685
      title: ''
      total_pages: 142
      order: 1
      base_file: 24AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
